---
ipv6_prefix: "2000::/56"

networks:
  - vid: 20
    bridge: false
    role: mesh
    name: mesh_network
    ipv6_subprefix: 0
    mesh_metric: 2048
    mesh_iface: mesh
    prefix: 10.12.2.0/24
    assignments:
      mountain-ap2: 2
      mountain-ap3: 3
      mountain-ap4: 4
      mountain-ap5: 5
      mountain-ap6: 6
    ipv6_assigments:
      mountain-ap2: 3
      mountain-ap3: 3
      mountain-ap4: 4
      mountain-ap5: 5
      mountain-ap6: 6
